# Generated by Django 5.1.1 on 2026-05-11 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefromcustomer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='messagefromcustomer',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagefromcustomer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagefromcustomer',
            name='subject',
            field=models.CharField(default='Feedback', max_length=255),
        ),
    ]
